# docker-compose.yml
version: "3.3"
services:

  web:
    image: nginx:latest
    ports:
      - "1080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: php
    build: ./docker/php
    links:
      - mysql_esp32
    ports:
      - 9000:9000
    volumes:
          - ./src:/var/www/html
    working_dir: /var/www/html

  mysql_esp32:
    image: mysql:8.0.27
    container_name: mysql_esp32
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: ESP32
      MYSQL_USER: ESP32_USER
      MYSQL_PASSWORD: ESP32_PASSWORD
    ports:
      - 1036:3306
    volumes:
      - ./docker/database/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql_esp32
    environment:
      PMA_HOST: mysql_esp32
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 1085:80