# docker-compose.yml
version: "3.3"
services:

  web:
    image: nginx:latest
    ports:
      - "1080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    container_name: php
    build: ./docker/php
    links:
      - mysql_esp32
      - mosquitto
    environment:
      MOSQUITTO_BROKER_URL: ${ESP32_MOSQUITTO_BROKER_URL}
      MOSQUITTO_BROKER_WEBSOCKET_PORT: ${ESP32_MOSQUITTO_BROKER_WEBSOCKET_PORT}
      MOSQUITTO_BROKER_USER: ${ESP32_MOSQUITTO_BROKER_USER}
      MOSQUITTO_BROKER_PASSWORD: ${ESP32_MOSQUITTO_BROKER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ESP32_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ESP32_MYSQL_DATABASE}
      MYSQL_USER: ${ESP32_MYSQL_USER}
      MYSQL_PASSWORD: ${ESP32_MYSQL_PASSWORD}
    ports:
      - 9000:9000
    volumes:
          - ./src:/var/www/html
    working_dir: /var/www/html

  mysql_esp32:
    image: mysql:8.0.27
    container_name: mysql_esp32
    environment:
      MYSQL_ROOT_PASSWORD: ${ESP32_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ESP32_MYSQL_DATABASE}
      MYSQL_USER: ${ESP32_MYSQL_USER}
      MYSQL_PASSWORD: ${ESP32_MYSQL_PASSWORD}
    ports:
      - 1036:3306
    volumes:
      - ./docker/database/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql_esp32
    environment:
      PMA_HOST: mysql_esp32
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 1085:80

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ./docker/mosquitto/config/:/mosquitto/config/
      - ./docker/mosquitto/log/:/mosquitto/log/
      - ./docker/mosquitto/data:/mosquitto/data/
    ports:
      - ${ESP32_MOSQUITTO_BROKER_PORT}:1883
      - ${ESP32_MOSQUITTO_BROKER_WEBSOCKET_PORT}:9001